'use client';
import { useState } from 'react';
import { ArrowRight, LockKeyhole } from 'lucide-react';
import { db } from '@/lib/supabase';
import { Feedback, Modal, Spinner, useAction } from './ui';
export default function Auth({ close, recovery = false }: { close: () => void; recovery?: boolean }) {
  const [mode, setMode] = useState<'signin' | 'signup' | 'reset' | 'update'>(recovery ? 'update' : 'signin');
  const action = useAction();
  const titles = { signin: 'Welcome to your neighborhood.', signup: 'A better bite starts here.', reset: 'Forgot your password?', update: 'Choose a new password.' };
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); await action.run(async () => {
    const email = String(form.get('email') || '').trim(); const password = String(form.get('password') || '');
    if (mode === 'signin') { const { error } = await db().auth.signInWithPassword({ email, password }); if (error) throw error; close(); }
    if (mode === 'signup') { const { data, error } = await db().auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/auth/callback` } }); if (error) throw error; if (data.session) close(); else action.setSuccess('Check your email for a confirmation link before signing in. If it does not arrive, email delivery may be temporarily limited.'); }
    if (mode === 'reset') { const { error } = await db().auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/auth/callback` }); if (error) throw error; action.setSuccess('If this email has an account, a reset link has been requested. Check your inbox and spam folder.'); }
    if (mode === 'update') { const { error } = await db().auth.updateUser({ password }); if (error) throw error; action.setSuccess('Password updated. You can close this window and continue.'); }
  }); }
  return <Modal title={mode === 'signup' ? 'Create an account' : mode === 'update' ? 'Reset password' : 'Your Halal Cart account'} close={close}><div className="auth-intro"><span className="eyebrow"><LockKeyhole size={14} /> ONE ACCOUNT. EVERY CORNER.</span><h3>{titles[mode]}</h3><p>{mode === 'reset' ? 'We’ll send a secure reset link to your email.' : 'Browse freely. Sign in to order, share a sighting, or run your cart.'}</p></div><form onSubmit={submit} className="form-stack">{mode !== 'update' && <label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" maxLength={254} required /></label>}{mode !== 'reset' && <label>{mode === 'update' ? 'New password' : 'Password'}<input name="password" type="password" autoComplete={mode === 'signin' ? 'current-password' : 'new-password'} minLength={mode === 'signin' ? 1 : 8} maxLength={128} placeholder={mode === 'signin' ? 'Your password' : 'At least 8 characters'} required /></label>}<Feedback error={action.error} success={action.success} /><button className="primary" disabled={action.busy}>{action.busy ? <Spinner /> : <ArrowRight size={18} />}{mode === 'signin' ? 'Sign in' : mode === 'signup' ? 'Create account' : mode === 'update' ? 'Update password' : 'Send reset link'}</button></form>{mode !== 'update' && <div className="auth-options"><button className="text-button" onClick={() => { setMode(mode === 'signup' ? 'signin' : 'signup'); action.setError(''); action.setSuccess(''); }}>{mode === 'signup' ? 'Already have an account? Sign in' : 'New here? Create an account'}</button>{mode === 'signin' && <button className="text-button" onClick={() => { setMode('reset'); action.setError(''); action.setSuccess(''); }}>Forgot password?</button>}{mode === 'reset' && <button className="text-button" onClick={() => setMode('signin')}>Back to sign in</button>}</div>}<p className="fine-print">By continuing, you agree to our <a href="/terms">Terms</a> and <a href="/privacy">Privacy policy</a>. No payment card is collected.</p></Modal>;
}
