'use client';
import WhatsAppOrder, { WhatsAppStates } from './whatsapp-order';
import { Clock3, ShoppingBag, RefreshCw } from 'lucide-react';
import { Cart, Order, OrderStatus, money } from '@/lib/types';
import { rpc } from '@/lib/supabase';
import { Empty, Feedback, Spinner, useAction } from './ui';
const labels: Record<OrderStatus, string> = { pending: 'Waiting for the cart', accepted: 'Order accepted', preparing: 'On the grill', ready: 'Ready for pickup', completed: 'Picked up', cancelled: 'Cancelled', rejected: 'Not accepted' };
const descriptions: Record<OrderStatus, string> = { pending: 'The cart needs to accept your order before preparing it.', accepted: 'The cart has accepted your order.', preparing: 'Your food is being prepared. Check back for pickup.', ready: 'Head to the cart and tell the owner your pickup name.', completed: 'Your pickup is complete. Thanks for eating local.', cancelled: 'This order was cancelled. No online payment was taken.', rejected: 'The cart could not take this order. No online payment was taken.' };
const next: Partial<Record<OrderStatus, OrderStatus[]>> = { pending: ['accepted', 'rejected'], accepted: ['preparing', 'cancelled'], preparing: ['ready', 'cancelled'], ready: ['completed'] };
const actionLabels: Partial<Record<OrderStatus, string>> = { accepted: 'Accept order', rejected: 'Decline', preparing: 'Start preparing', ready: 'Mark ready', completed: 'Complete pickup', cancelled: 'Cancel order' };
export function OrderCard({ order, cart, owner = false, reload }: { order: Order; cart?: Cart; owner?: boolean; reload: () => Promise<void> }) { const action = useAction(); return <article className={`order-card ${order.status === 'ready' ? 'ready' : ''}`}><div className="row between"><span className={`status status-${order.status}`}><span className="dot" />{labels[order.status]}</span><span className="muted small">#{order.id.slice(0, 8).toUpperCase()}</span></div><h3>{owner ? order.pickup_name : cart?.name || 'Your cart'}</h3><p className="muted small">{new Date(order.created_at).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })} · Pickup for {order.pickup_name}</p><p className="order-description">{descriptions[order.status]}</p><div className="order-lines">{order.order_items?.map(item => <div className="row between" key={item.id}><span><strong>{item.quantity}×</strong> {item.name}</span><span>{money(item.quantity * item.unit_price_cents)}</span></div>)}</div>{order.notes && <p className="order-note"><strong>Note:</strong> {order.notes}</p>}<div className="row between order-total"><strong>{money(order.total_cents)}</strong><span className="small">Pay at cart · unpaid online</span></div>{!owner && cart?.latitude && cart.longitude && !['completed', 'cancelled', 'rejected'].includes(order.status) && <a className="button secondary full" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${cart.latitude},${cart.longitude}`}>Directions to last shared location ↗</a>}{!owner && <WhatsAppOrder orderId={order.id} />}<Feedback error={action.error} /><div className="row wrap">{(owner ? next[order.status] || [] : order.status === 'pending' ? ['cancelled' as OrderStatus] : []).map(status => <button key={status} disabled={action.busy} className={['cancelled', 'rejected'].includes(status) ? 'secondary danger-text' : 'primary'} onClick={() => action.run(async () => { await rpc('transition_order', { p_order_id: order.id, p_status: status }); await reload(); })}>{action.busy ? <Spinner /> : null}{actionLabels[status]}</button>)}</div></article>; }
export default function Orders({ orders, carts, signedIn, signIn, reload, loading }: { orders: Order[]; carts: Cart[]; signedIn: boolean; signIn: () => void; reload: () => Promise<void>; loading: boolean }) { return <section className="content-section"><div className="section-heading"><div><span className="eyebrow">FROM GRILL TO GO</span><h1>Your pickup orders</h1><p>Follow your order from the first sizzle to the last handoff.</p></div>{signedIn && <button className="secondary" onClick={reload} disabled={loading}><RefreshCw size={17} className={loading ? 'spin' : ''} />Refresh</button>}</div>{!signedIn ? <Empty icon={<ShoppingBag />} title="Your next meal is one sign-in away." action={<button className="primary" onClick={signIn}>Sign in to see orders</button>}>Your orders are private. Sign in to place an order and follow its progress.</Empty> : loading && !orders.length ? <div className="loading"><Spinner />Loading your orders…</div> : !orders.length ? <Empty icon={<Clock3 />} title="Nothing on the grill. Yet.">Find a cart, pick your favorites, and your pickup order will appear here.</Empty> : <><p className="live-note"><span className="dot" /> Updates automatically every 15 seconds · Payment is collected by the cart.</p><WhatsAppStates orderIds={orders.map(order => order.id)}><div className="order-grid">{orders.map(order => <OrderCard key={order.id} order={order} cart={carts.find(cart => cart.id === order.cart_id)} reload={reload} />)}</div></WhatsAppStates></>}</section>; }
