'use client';
import { createContext, useContext, useEffect, useState, useCallback } from 'react';
import { rpc } from '@/lib/supabase';
const NotificationContext = createContext<{ states: Record<string, string>; refresh: () => void }>({ states: {}, refresh: () => {} });
export function WhatsAppStates({ orderIds, children }: { orderIds: string[]; children: React.ReactNode }) {
 const [states, setStates] = useState<Record<string, string>>({}); const ids = orderIds.join(',');
 const load = async (value: string) => { const list = value.split(','); const result: Record<string, string> = {}; for (let i = 0; i < list.length; i += 100) Object.assign(result, await rpc<Record<string, string>>('whatsapp_order_states', { p_order_ids: list.slice(i, i + 100) })); return result; };
 const refresh = useCallback(() => { if (!ids) return; load(ids).then(setStates).catch(() => {}); }, [ids]);
 useEffect(() => { let active = true; const update = () => { if (!ids) return; load(ids).then(value => { if (active) setStates(value); }).catch(() => {}); }; const visible = () => { if (document.visibilityState === 'visible') update(); }; update(); window.addEventListener('focus', update); document.addEventListener('visibilitychange', visible); return () => { active = false; window.removeEventListener('focus', update); document.removeEventListener('visibilitychange', visible); }; }, [ids]);
 return <NotificationContext.Provider value={{ states, refresh }}>{children}</NotificationContext.Provider>;
}
export default function WhatsAppOrder({ orderId }: { orderId: string }) {
 const { states, refresh } = useContext(NotificationContext); const state = states[orderId]; const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [link, setLink] = useState('');
 if (!state) return null;
 return <div className="notice"><p>{state === 'active' ? 'WhatsApp updates enabled. Delivery may be delayed; follow this page for the latest status.' : state === 'stopped' ? 'WhatsApp updates stopped.' : state === 'paused' ? 'WhatsApp updates are temporarily unavailable. Track your order here.' : 'WhatsApp updates are not active. Verify your number to enable them.'}</p>{state === 'unverified' && <>{link ? <a className="button secondary" target="_blank" rel="noreferrer" href={link}>Open WhatsApp and send verification ↗</a> : null}<button className="secondary" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { const value = await rpc<{ activation_code: string; business_number: string }>('renew_whatsapp_verification', { p_order_id: orderId }); setLink(`https://wa.me/${value.business_number}?text=${encodeURIComponent(`VERIFY ${value.activation_code}`)}`); } catch { setError('Verification is unavailable. Continue tracking your order here.'); } finally { setBusy(false); } }}>{link ? 'Generate a fresh verification link' : 'Verify my WhatsApp number'}</button><p className="fine-print">Send the prefilled message from your submitted number within 30 minutes. Consent expires if unverified for 24 hours.</p></>}{state !== 'stopped' && <button className="secondary" disabled={busy} onClick={async () => { setBusy(true); try { await rpc('withdraw_whatsapp', { p_order_id: orderId }); setLink(''); refresh(); } catch { setError('Could not stop updates. Try again, or reply STOP in WhatsApp.'); } finally { setBusy(false); } }}>Stop WhatsApp updates</button>}{error && <p role="alert">{error}</p>}</div>;
}
