export type Cart = { id: string; owner_id: string; name: string; description: string; cuisine: string; address: string; latitude: number | null; longitude: number | null; is_online: boolean; location_updated_at: string | null; };
export type MenuItem = { id: string; cart_id: string; name: string; description: string; price_cents: number; category: string; is_available: boolean; sort_order: number; };
export type Sighting = { id: string; name: string; address: string; latitude: number; longitude: number; notes: string; created_at: string; };
export type OrderStatus = 'pending' | 'accepted' | 'preparing' | 'ready' | 'completed' | 'rejected' | 'cancelled';
export type Order = { id: string; cart_id: string; customer_id: string; pickup_name: string; notes: string; total_cents: number; status: OrderStatus; payment_status: string; created_at: string; order_items: { id: string; name: string; quantity: number; unit_price_cents: number }[] };
export const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value / 100);
export const online = (cart: Cart) => cart.is_online && !!cart.location_updated_at && Date.now() - new Date(cart.location_updated_at).getTime() < 15 * 60 * 1000;
export function age(date: string | null) { if (!date) return 'Location not yet shared'; const minutes = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 60000)); return minutes < 1 ? 'Updated just now' : minutes < 60 ? `Updated ${minutes} min ago` : new Date(date).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
export function distance(lat: number, lng: number, otherLat: number, otherLng: number) { const r = Math.PI / 180; const a = Math.sin((otherLat - lat) * r / 2) ** 2 + Math.cos(lat * r) * Math.cos(otherLat * r) * Math.sin((otherLng - lng) * r / 2) ** 2; return 3959 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
export function location(): Promise<GeolocationPosition> { return new Promise((resolve, reject) => { if (!navigator.geolocation) { reject(new Error('Location is unavailable on this device. Enter coordinates manually.')); return; } navigator.geolocation.getCurrentPosition(resolve, () => reject(new Error('Location could not be accessed. Check browser permissions or enter your location manually.')), { enableHighAccuracy: true, timeout: 15000, maximumAge: 30000 }); }); }
